---
title: "Lab 1"
author: "Naixing Huang"
date: "2023-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results='hide', warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(extrafont)
library(here)
```

```{r}
hot_dogs <- read_csv(here::here("data", "hot_dog_contest.csv"), 
    col_types = cols(
      gender = col_factor(levels = NULL)
    ))
library(skimr)

```

```{r}
hot_dogs <- hot_dogs %>% 
  mutate(Post_ifoce = year >= 1997) %>% 
  filter(year >= 1981 & gender == 'male')
```


```{r}
with_affil <- read_csv(here::here("data", "hot_dog_contest_with_affiliation.csv"), 
                          col_types = cols(affiliated = col_factor(),
                                             gender = col_factor()))%>% 
  mutate(post_ifoce = year >= 1997) %>% 
  filter(year >= 1981 & gender == "male") 
#or

hdm_affil <- read_csv(here::here("data", "hot_dog_contest_with_affiliation.csv"), 
    col_types = cols(
      affiliated = col_factor(levels = NULL), 
      gender = col_factor(levels = NULL)
      )) %>% 
  mutate(post_ifoce = year >= 1997) %>% 
  filter(year >= 1981 & gender == "male") 

```




```{r}
affil_plot <- ggplot(hdm_affil, aes(x = year, y = num_eaten)) + 
  geom_col(aes(fill = affiliated),colour = "white") + 
  labs(x = "Year", y = "Hot Dogs and Buns Consumed") +
  ggtitle("Nathan's Hot Dog Eating Contest Results, 1981-2022", subtitle = "(Male contestants only)") +
  scale_fill_manual(values = c('#E9602B','#2277A0','#CCB683'),
                    name = "IFOCE-affiliation")

```


```{r}
affil_plot <- affil_plot + 
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 80, 10)) +
  scale_x_continuous(expand = c(0, 0))

```

```{r}
affil_plot <- affil_plot + 
  coord_cartesian(xlim = c(1980, 2023), ylim = c(0, 80)) 


#or
affil_plot <- affil_plot + 
  coord_cartesian(xlim = c(1979, 2023), ylim = c(0, 80)) 
```





```{r}
new_y <- seq(from = 1981, to = 2022, by = 5) 



hd_years <- hdm_affil %>%
  distinct(year) %>% 
  mutate(year_lab = ifelse(year %in% new_y, year, ""))

theme_hd <- theme(plot.title = element_text(hjust = 0.5),
                     axis.text = element_text(size = 12),
                     panel.background = element_blank(),
                     axis.line.x = element_line(color = "gray80", size = 0.5),
                     axis.ticks = element_line(color = "gray80", size = 0.5),
                     text = element_text(family = "Palatino")
                     )


```



```{r}
nathan_plot <- ggplot(hdm_affil, aes(x = year, y = num_eaten)) + 
  geom_col(aes(fill = affiliated)) + 
  labs(x = "Year", y = "Hot Dogs and Buns Consumed") +
  ggtitle("Nathan's Hot Dog Eating Contest Results, 1981-2022", subtitle = "(Male contestants only)") +
  scale_fill_manual(values = c('#E9602B','#2277A0','#CCB683'),
                    name = "IFOCE-affiliation") + 
  theme_hd +
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 80, 10)) +
  scale_x_continuous(expand = c(0, 0), 
                     breaks = hd_years$year,
                     labels = hd_years$year_lab) + 
  coord_cartesian(xlim = c(1980, 2023), ylim = c(0, 80))
```


```{r}
nathan_ann <- nathan_plot +
  guides(fill="none") + # turn off the legend/guide for the "fill" aesthetic
  coord_cartesian(xlim = c(1980, 2023), ylim = c(0, 90)) +
  annotate('segment', x=1980.75, xend=2000.25, y= 30, yend=30, linewidth=0.5, color="#CCB683")+
  annotate('segment', x=1980.75, xend=1980.75, y= 30, yend=28, linewidth=0.5, color="#CCB683") +
  annotate('segment', x=2000.25, xend=2000.25, y= 30, yend=28, linewidth=0.5, color="#CCB683") +
  annotate('segment', x=1990, xend=1990, y= 33, yend=30, linewidth=0.5, color="#CCB683") +
  annotate('text', x=1990, y=36, label="No MLE/IFOCE Affiliation", color="#CCB683", family="Lato", hjust=0.5, size = 3) +



  annotate('segment', x=2000.75, xend=2006.25, y= 58, yend=58, linewidth=0.9, color="#2277A0") +
  annotate('segment', x=2000.75, xend=2000.75, y= 58, yend=56, linewidth=0.9, color="#2277A0") +
  annotate('segment', x=2006.25, xend=2006.25, y= 58, yend=56, linewidth=0.9, color="#2277A0") +
  annotate('segment', x=2003.5, xend=2003.5, y= 61, yend=58, linewidth=0.5, color="#2277A0") +
  annotate('text', x=2003.5, y=65, label="MLE/IFOCE\nFormer Member", color="#2277A0", family="Lato", hjust=0.5, size = 3) +


  annotate('segment', x=2006.75, xend=2022.25, y= 79, yend=79, linewidth=1.9, color="#E9602B") +
  annotate('segment', x=2006.75, xend=2006.75, y= 79, yend=77, linewidth=1.9, color="#E9602B") +
  annotate('segment', x=2022.25, xend=2022.25, y= 79, yend=77, linewidth=1.9, color="#E9602B") +
  annotate('segment', x=2015, xend=2015, y= 82, yend=79, linewidth=0.5, color="#E9602B") +
  annotate('text', x=2015, y=86, label="MLE/IFOCE Current Member", color="#E9602B", family="Palatino", hjust=0.5, size = 3)
```
```{r}
hdm_females <- read_csv(here::here("data", "hot_dog_contest_with_affiliation.csv"), 
    col_types = cols(
      affiliated = col_factor(levels = NULL), 
      gender = col_factor(levels = NULL)
      )) %>% 
  mutate(post_ifoce = year >= 1997) %>% 
  filter(year >= 1981 & gender == "female") 
```

```{r}
nathan_w_females <- nathan_ann +
  geom_col(data = hdm_females, 
           width = 0.9, 
           fill = "#F68A39") +
  labs(subtitle = NULL)
```


```{r}
caption <- paste(strwrap("* From 2011 on, separate Men's and Women's prizes have been awarded. All female champions to date have been MLE/IFOCE-affiliated.", 70), collapse="\n")

myplot <- nathan_w_females +
  annotate('text', x = 2011, y = 36, label="*", family = "Palatino", size = 12) +
  labs(caption = caption) +
  theme(plot.caption = element_text(family = "Palatino", size=8, hjust=0, margin=margin(t=15)))
myplot
```






